

# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
compiler: gcc
pandoc_version: 1.18

sudo: required
cache: packages

addons:
  apt:
    packages:
      - python2.7

env:
  global:
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"
    
before_install:

  - sudo apt-get install r-base-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get update -qq
  - sudo apt-get install -y cmake
  - sudo pip install --upgrade pip setuptools
  - sudo pip install -U numpy
  - sudo pip install --upgrade scipy
  - sudo pip install -U scikit-learn
  - git clone https://github.com/RGF-team/rgf.git
  - cd rgf/python-package
  - sudo python setup.py install
  - cd 
  - sudo apt-get update
 
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# workaround : no idea why the same .travis.yml file as in fuzzywuzzyR package doesn't work ( it gives "No DESCRIPTION file found, user must supply their own install and script steps" ) 
  
install:

  - Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "covr", "knitr", "rmarkdown", "reticulate", "R6", "Matrix"))'
  
script:

  - cd /home/travis/build/mlampros/
  - Rscript -e 'system("R CMD build RGF")'
  - Rscript -e 'system("R CMD check RGF_1.0.4.tar.gz")'
  - cd
  
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
after_success:
  - Rscript -e 'covr::codecov(path = "/home/travis/build/mlampros/RGF", quiet = FALSE)'
  
warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
